### ISSUE TITLE
Ability to comment not available when Articles have 'inline pictures.

### ISSUE THREAD

**Issue by david-unwin** [akeeba/engage#132]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue
1. go to https://cirenopenair.org.uk/news/29-news/60-new-pool-panel-paintings here you will see the problem - There is no login to  or if you are logged in you cannot see the form to enter your comments
2. Whereas if you go to https://cirenopenair.org.uk/news/29-news/58-pool-autumn-update . This article does not have any inline images and the comment feature works fine
3. I have attached 2 images of the issue the first is without image and the 2nd with image inline
![article - no image](https://user-images.githubusercontent.com/95095238/145992237-eee1e97f-479f-4f18-b8b6-a53028957799.png)
![article - with image](https://user-images.githubusercontent.com/95095238/145992468-3c25813a-ad43-43e9-9bac-9ccef62f7cb1.png)

Be specific. You may link to one or more screenshots or a video as long as it's not the only clue you leave. Use words to describe what happens.

### Expected result

What you believed should have happened following the steps you outlined above.

### Actual result

What actually happened.

### Troubleshooting already performed

Please tell us about any troubleshooting you already performed and its results.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.10.3
* **PHP version**: 7.4
* **Am I using HTTPS**: Yes 
* **Server Operating System**: Linux
* **My device's Operating System**: Windows
* **My device's Operating System version**: 10
* **Browser**: Chrome
* **Browser version**: Version 96.0.4664.93

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: x.y.z
* **Server type**: Apache, NginX, IIS, Lighttpd, LiteSpeed, ...
* **Server version**: x.y.z
* **Hosting company / Local server**: Enter the name of your site's hosting company or the prepackaged local server (e.g. MAMP, XAMPP, WAMPServer, ...) that you're using
* **Server Operating System version**: e.g. Windows 10, Ubuntu 16.04, ... Type N/A if it's a live host and you have no idea.

**Comment by nikosdion** [comment]
Inline images are completely irrelevant. Never mind that I know how Engage works, you can also see how inline images have nothing to do with the ability to comment [on my own blog](https://www.dionysopoulos.me/iis-development-server-for-php-on-windows-10.html).

Most likely you closed the comments for this article or you have enabled the option to automatically close the comments after a certain period of time. I can't help but observe that the article where comments are not possible is more than 6 months old whereas the article you can comment on is under 2 months old. If your comments auto–close period is between 2 and 6 months that would explain it.

**Comment by david-unwin** [comment]
Nicholas,
Apologies! The global setting for comments was set to 0. However, for our News Articles category (which I reported), it was set to 120 which exceeded the date on the articles in question. I don't remember setting that, but I suppose I must have?? I set that to 0 and now I can see the comment feature.
Again, apologies for reporting this as bug!
Kind regards

**Comment by nikosdion** [comment]
No worries :) Have a great day!
