### ISSUE TITLE
i get a lot of spam commets

### ISSUE THREAD

**Issue by Jumbo125** [akeeba/engage#134]
Hy
I tried your great extension and get every day a lot of spam commets. I use recaptcha and the commets will be only displayd, if the are from admins. But it didn't help.
Can i disallow some ip-adresses, because the commets are always from the same ip-adresses. (5-8 diffrent ips)

Thank you

**Comment by Jumbo125** [comment]
sorry for wrong label

**Comment by nikosdion** [comment]
You can't disallow IPs directly. You can do that [through your site's .htaccess file](https://htaccessbook.com/block-ip-address/) or with a third party extensions like our own Admin Tools Professional.

However, I would instead recommend using the Akismet integration. It auto–deletes blatant spam comments and marks possible spam as such. For a non–commercial site it is free of charge. For commercial sites there is a charge but it's really not that much. On my own blog it totally killed off all the spam.

PS: Don't worry about the issue label, I always spot and fix these :)

**Comment by Jumbo125** [comment]
okay. thank you a lot!

**Comment by Jumbo125** [comment]
i had block the ip adresses by php. wokrs great!

**Comment by nikosdion** [comment]
Whatever works best for you :)
