### ISSUE TITLE
Gravatar missing in pkg_engage.xml (3.0.1)

### ISSUE THREAD

**Issue by NetSecond** [akeeba/engage#152]
Hi,

I was wondering, why gravatar status in joomla extension list is 2.0.5 after update to 3.0.1.

Then I checked the file pkg_engage.xml:

```
        <!-- Plugins: engage -->
        <file type="plugin" group="engage" id="akismet">plg_engage_akismet.zip</file>
        <file type="plugin" group="engage" id="email">plg_engage_email.zip</file>
```
There is missing:

```
        <file type="plugin" group="engage" id="gravatar">plg_engage_gravatar.zip</file>
```

After I completed it, gravatar is shown as version 3.0.1 too.

Regards
NetSecond

**Comment by nikosdion** [comment]
Oops! You are right. I will fix it in a few minutes

**Comment by nikosdion** [comment]
Fixed with https://github.com/akeeba/engage/commit/e709a4f3042ab14424f8c60eac75e8704c121877
