### ISSUE TITLE
Yes / No Buttons green all the time (3.0.2)

### ISSUE THREAD

**Issue by NetSecond** [akeeba/engage#159]
If I change an option from yes (ja) to no (nein), the button don´t switch from green to red (or grey ??).

Edit: This is only in engage module/options.
In other modules or rest of Joomla it works correct (green/grey).
Edit 2: Its only at the articles options for comments, in engage options it is working.

### Steps to reproduce the issue
Change in backend an option from yes to no and back, it always will be green.

### Actual result
No change from green to red, it is always green.

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.0.5
* **PHP version**: 8.0.8
* **Am I using HTTPS**: Yes
* **Server Operating System**: Ubuntu Server 64 Bit
* **My device's Operating System**: Windows
* **My device's Operating System version**: Windows 10
* **Browser**: Chrome, Firefox, Edge, Internet Explorer, Safari, Opera
* **Browser version**: newest

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**:  Ver 15.1 Distrib 10.5.13-MariaDB
* **Server type**: Apache 2
* **Server version**: 2.4.48 (Ubuntu)
* **Hosting company / Local server**: Own Hosting
* **Server Operating System version**: Ubuntu Server 64 Bit

![yesnogreen](https://user-images.githubusercontent.com/26506313/148662392-55cb9339-470a-4ba2-b17a-f22c74b96578.jpg)

**Comment by nikosdion** [comment]
This is controlled by Joomla itself. We simply use its radio XML form element with the layout provided by Joomla to turn it into a switcher. For what it's worth, I cannot reproduce this on Joomla 4.0.5 using any modern browser.

**Comment by NetSecond** [comment]
Ok, thank you, after your change for 3.0.3 its working fine now.
