### ISSUE TITLE
Comment nesting is not shown on frontpage (3.0.2)

### ISSUE THREAD

**Issue by NetSecond** [akeeba/engage#161]
### Steps to reproduce the issue

Set in the engage options "Maximum comment nesting" for example to 3 and make some comments under existing comments (as replies).
The reply comments are on same horizontal place like main comment.

![nesting](https://user-images.githubusercontent.com/26506313/148694907-7702007b-14d4-4fa8-bd25-1819c61b09fe.jpg)

**Comment by nikosdion** [comment]
You need to load the custom CSS. It's an option.

The default layout, without additional CSS, works on templates based on Bootstrap 5 e.g. Cassiopeia. If you don't have such a template you need to load the custom CSS. It's documented https://github.com/akeeba/engage/wiki/Component-options

> Load custom CSS. By default, Akeeba Engage uses Bootstrap 5 CSS classes to style the comments in the frontend of your site. If you are using a template which does not use Bootstrap 5 classes enable this option. This will load the custom CSS file media/com_engage/css/comments.css (or its template override). You can take a look at our CSS and its SCSS source file to see how you can easily format comments yourself.

**Comment by NetSecond** [comment]
Ah, ok, thank you, I will try.

**Comment by NetSecond** [comment]
Ok, doesn´t work too, it looks different but nesting isn´t working.
So maybe I have to look in CSS files ....

**Comment by NetSecond** [comment]
Now I have installed joomlart T4 Framework and Bootstrap 5 Blank Page, but nesting isn´t working.
So now I leave it as it is.

**Comment by nikosdion** [comment]
Fixed with https://github.com/akeeba/engage/commit/9f28b6605acecec5ccdd075fa4d0a5bfdf0e05b7

**Comment by NetSecond** [comment]
Ok, in 3.0.3 it is working now (custom CSS) but why is it in dark mode and how can I change it to normal mode ??

**Comment by nikosdion** [comment]
> why is it in dark mode

Your browser settings. See [this presentation](https://www.dropbox.com/s/3vt5ogbzorvxlh5/Hello%20darkness%2C%20my%20old%20friend.pdf?dl=0), slides 23 and 25.

>  how can I change it to normal mode

If only [someone had already documented this](https://github.com/akeeba/engage/wiki/Customising-CSS)... 😉

**Comment by NetSecond** [comment]
Ah, ok, I thought the color depends on the website.
My Website is in white (in browser dark mode too) and black engage looks strange.
But thanks for the solution.
