### ISSUE TITLE
Use Global CAPTCHA option is not applied

### ISSUE THREAD

**Issue by NetSecond** [akeeba/engage#162]
Since update to 3.0.2, invisible captcha is not working like in 2.0.5.

![captcha](https://user-images.githubusercontent.com/26506313/148695156-6d907762-c1c9-4f1f-b634-e9e8a2e9824a.jpg)

Nothing shown in right bottom corner in frontpage like before update.

**Comment by nikosdion** [comment]
**CANNOT** confirm as described.

![Screen Shot 2022-01-10 at 17 32 28](https://user-images.githubusercontent.com/256041/148792642-1cf90f08-880c-44e5-9a88-68cdb3c2ade1.png)

![Screen Shot 2022-01-10 at 17 32 57](https://user-images.githubusercontent.com/256041/148792744-f276f627-b9ba-439f-bd67-64f8be22e81f.png)

It does look, however, that the Use Global option is not applied which is a very different and far less important issue. If you click on this drop–down and select a specific captcha setting it will still work, therefore you don't need to wait for a new release.

**Comment by nikosdion** [comment]
I changed the title to reflect the actual problem that needs to be solved i.e. the Use Global option not working versus the entire CAPTCHA feature not working.

**Comment by NetSecond** [comment]
Ok, I changed to NonGlobal Captcha option and its working fine.

But I see this under the message field:

COM_ATS_TICKET_LBL_CAPTCHA_LABEL *

Where do I find it ??

Edit:
Ok, looks like a JCE translation problem, sorry.

Edit 2:
I found this variable in: /components/com_engage/forms/comment_new.xml

It doesn´t matter if I have the system in english or german.
So it looks like, the variable is missing in language definitions ?!?!

**Comment by NetSecond** [comment]
Ok, I found the label problem for COM_ATS_TICKET_LBL_CAPTCHA_LABEL:

The variable is missing in all language files maybe in this file: /administrator/language/xx-XX/com_engage.ini

If I place the variable there at the top of the file with the value eg. "Captcha", then I will see the word "Captcha *" instead of the variable lable name.

**Comment by NetSecond** [comment]
Is this correct ??

```
[Common]
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;>
;; Common language strings
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;>
COM_ENGAGE="Akeeba Engage"
COM_ATS_TICKET_LBL_CAPTCHA_LABEL="Captcha"
```

Please see last line ....

**Comment by nikosdion** [comment]
**DO NOT THAT LANGUAGE STRING**. The label attribute is a typo and will be removed. 

It should also not have been printed by Joomla anyway since we already tell it hiddenLabel=true. In fact, it's not printed on my dev site using Cassiopeia. I think your template has a broken layout override which ignores this XML Form option (there's an overridable layout which has to honour this option). That's all there is to it.

**Comment by NetSecond** [comment]
Ok, thanks for the info.
