### ISSUE TITLE
Can not reply to comment

### ISSUE THREAD

**Issue by modernmagic** [akeeba/engage#164]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

1. Click Reply
2. Fill in name and email address.
3. ISSUE: The text field does not allow me to add text.
https://help.thinkiq.com/blog/test-post#akengageCommentForm

### Expected result

I expected to see a editor.

### Actual result

The editor field is blank.

### Troubleshooting already performed

I switched from JCE Pro 2.9.18 to TinyMCE to get it to work.  

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.10.4
* **PHP version**: 7.4.27
* **Am I using HTTPS**: Yes
* **Server Operating System**: Siteground
* **My device's Operating System**: macOS
* **My device's Operating System version**: macOS Catalina
* **Browser**: Chrome
* **Browser version**: 96.0.4664.110

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 5.7.32-35-log
* **Server type**: ?
* **Server version**: ?
* **Hosting company / Local server**: Siteground
* **Server Operating System version**: ?

### Additional comments

We prefer to use JCE Pro.  Does Engage work with JCE?

**Comment by nikosdion** [comment]
Hi! I haven't seen you in a while, I think since the Joomla World Conference about a decade ago before you changed your name. How are you doing?

Well, back to your issue. You need to configure JCE with a profile for Guest users. By default, JCE only has a frontend profile for Registered and above. Add Guest there and you'll be set. Same idea as configuring TinyMCE.

I will close this issue as invalid — since JCE configuration is outside our control — but you can still reply here.

**Comment by nikosdion** [comment]
I updated the documentation page to also include instructions for JCE: https://github.com/akeeba/engage/wiki/Setting-up-your-HTML-editor

**Comment by modernmagic** [comment]
Nicholas ,

Wow! Coincidentally I just used my 2012 JWC t-shirt as a rag the other day to clean my surfboard.  But only because we are minimalising our lives and preparing to become world travelers!  Joomla has allowed me to be financially independent and support myself and my children.

My business still solely focus on building Joomla sites and its growing every year.  modernmagic.com <https://www.modernmagic.com/>

And a part of my success is due to you and your extensions.  THANK YOU SO MUCH.  :-)

I just setup the Guest profile and it works perfectly.  Thank you!
Odin
