### ISSUE TITLE
500 Layout phpversion_warning not found.

### ISSUE THREAD

**Issue by 80cents** [akeeba/engage#165]
Hello, I am using XAMPP on PC to test out Joomla 4 and Akeeba Engage 3. I follow installation instructions and ensure important plugins turned on. Everything is okay and no error.
I try to write first comment. No error at the frontend and saw message "Your comment was posted successfully.".

However, when I go to admin area, Akeeba Engage component gave me this error that 500 Layout phpversion_warning not found.
What could be the problem? Thank you.

Akeeba Engage - An unhandled Exception has been detected
500 Layout phpversion_warning not found.
File &lt;root&gt;\administrator\components\com_engage\src\View\Mixin\LoadAnyTemplate.php Line 234

 The content below this point is for developers and power users.

Joomla 4.0.6 – PHP 8.1.1 on WINNT

Debug information
Exception type: Exception

#0 C:\xampp\htdocs\80cents\administrator\components\com_engage\src\View\Mixin\LoadAnyTemplate.php(99): Akeeba\Component\Engage\Administrator\View\Comments\HtmlView->loadTemplate('warning', false, Array)
#1 C:\xampp\htdocs\80cents\administrator\components\com_engage\tmpl\comments\default.php(41): Akeeba\Component\Engage\Administrator\View\Comments\HtmlView->loadAnyTemplate('common/phpversi...', false, Array)
#2 C:\xampp\htdocs\80cents\administrator\components\com_engage\src\View\Mixin\LoadAnyTemplate.php(224): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\80cents\libraries\src\MVC\View\HtmlView.php(218): Akeeba\Component\Engage\Administrator\View\Comments\HtmlView->loadTemplate(NULL)
#4 C:\xampp\htdocs\80cents\administrator\components\com_engage\src\View\Comments\HtmlView.php(140): Joomla\CMS\MVC\View\HtmlView->display(NULL)
#5 C:\xampp\htdocs\80cents\libraries\src\MVC\Controller\BaseController.php(692): Akeeba\Component\Engage\Administrator\View\Comments\HtmlView->display()
#6 C:\xampp\htdocs\80cents\administrator\components\com_engage\src\Controller\Mixin\ControllerEvents.php(74): Joomla\CMS\MVC\Controller\BaseController->display()
#7 C:\xampp\htdocs\80cents\libraries\src\Dispatcher\ComponentDispatcher.php(146): Akeeba\Component\Engage\Administrator\Controller\CommentsController->execute('main')
#8 C:\xampp\htdocs\80cents\administrator\components\com_engage\src\Dispatcher\Dispatcher.php(75): Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()
#9 C:\xampp\htdocs\80cents\libraries\src\Component\ComponentHelper.php(389): Akeeba\Component\Engage\Administrator\Dispatcher\Dispatcher->dispatch()
#10 C:\xampp\htdocs\80cents\libraries\src\Application\AdministratorApplication.php(143): Joomla\CMS\Component\ComponentHelper::renderComponent('com_engage')
#11 C:\xampp\htdocs\80cents\libraries\src\Application\AdministratorApplication.php(186): Joomla\CMS\Application\AdministratorApplication->dispatch()
#12 C:\xampp\htdocs\80cents\libraries\src\Application\CMSApplication.php(278): Joomla\CMS\Application\AdministratorApplication->doExecute()
#13 C:\xampp\htdocs\80cents\administrator\includes\app.php(63): Joomla\CMS\Application\CMSApplication->execute()
#14 C:\xampp\htdocs\80cents\administrator\index.php(32): require_once('C:\\xampp\\htdocs...')
#15 {main}

**Comment by Razerr** [comment]
I have an similar error response but in a different place.   

```
Akeeba Engage - An unhandled Exception has been detected
500 Joomla\Plugin\Actionlog\Engage\Extension\Engage::getCommentInfo(): Argument #1 ($comment) must be of type Joomla\CMS\Table\Table, Akeeba\Component\Engage\Site\Controller\CommentsController given, called in /home/admin/web/mywebsite/public_html/plugins/actionlog/engage/src/Extension/Engage.php on line 311

File &lt;root&gt;/plugins/actionlog/engage/src/Extension/Engage.php Line 361

The content below this point is for developers and power users.

Joomla 4.0.6 – PHP 8.0.10 on Linux 
```
I am on a live site and it happens when i click the unpublish button under a comment.

**Comment by nikosdion** [comment]
Fixed with https://github.com/akeeba/engage/commit/23929f079fd48793fef920f5c1276153e0505f9b

**Comment by nikosdion** [comment]
@Razerr Your issue is **COMPLETELY** unrelated. Unpublish the Action Log plugin for Akeeba Engage.

People, just because you see "Exception" or "Error" doesn't mean it's all the same. It's like saying that a bullethole in the head and poisoning are the same cause of death. Yeah, both are dead but if someone says both people died from the same cause it sounds ridiculous, don't it? :)

In any case, this is something I will fix tomorrow. It's already past midnight here.

**Comment by Razerr** [comment]
@nikosdion I'm sorry. Actually I had another problem but trying to find out what's wrong noticed this and I thought it was something important without looking any further :(
