### ISSUE TITLE
Don't have a comment button

### ISSUE THREAD

**Issue by adoewa** [akeeba/engage#175]
I installed engage to show only on blog articles.
I see the "no toughts on ..." tag, but no button to add comment.

https://www.schoonheidsateljeetje.be/blog

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.10.5
* **PHP version**: 7.4
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows
* **My device's Operating System version**: W10
* **Browser**: Chrome
* **Browser version**: 97.0.4692.99 

#### Good to have information

Kind regards, Koen

**Comment by nikosdion** [comment]
You need to tell Joomla who has the permission to submit comments as explained in the [documentation](https://github.com/akeeba/engage/wiki/Installation-and-Setup-Guide#tell-akeeba-engage-who-can-submit-and-manage-comments). I quote the linked page:

> Joomla has a very thorough permissions system since version 1.6. Akeeba Engage uses it to determine who can do what with comments. In fact, Akeeba Engage uses the same internal permissions names as Joomla. This means that unless you explicitly tell Joomla otherwise, Akeeba Engage's permissions track the default permissions for Joomla as set in the Global Configuration page. Therefore the default state on most sites is that only Manager and above can file comments, just like Manager and above can submit new articles.

**Comment by adoewa** [comment]
Thanks Nicolas...

The only problem i still have is that i cannot type anything in the comment field...

Koen

**Comment by nikosdion** [comment]
You really need to read the documentation. https://github.com/akeeba/engage/wiki/Setting-up-your-HTML-editor
