### ISSUE TITLE
[DOCS]: Various typo fixes & updates to text filter wordings

### ISSUE THREAD

**Issue by RCheesley** [akeeba/engage#200]
### Documentation page affected

A few!

* Home
* Component options
* Install & setup guide
* Main concepts
* Setting up HTML editor

### Your concern

Thanks for making this open source and for the very detailed documentation, really helpful in getting set up and configured! I found a few typos and also that Joomla has changed the text filters from Blacklist/Whitelist so I have also updated that.

I was not able to make a PR to update the wiki, so you can find my updates on this branch of my fork: https://github.com/RCheesley/engage/tree/fixing-typos

Hope it's helpful!

**Comment by nikosdion** [comment]
Thank you very much, Ruth! I have merged your changes into our wiki.

Have a great evening!
