### ISSUE TITLE
Error in module mod_engage_latest

### ISSUE THREAD

**Issue by pinochico** [akeeba/engage#201]
in tmel/default.php

is error in line 76:

`(new \Joomla\CMS\Date\Date($comment->created_on))->format(Text::_('DATE_FORMAT_LC2'))`

With this is result actually date and time every date :)

Right code is:

`(new \Joomla\CMS\Date\Date($comment->created))->format(Text::_('DATE_FORMAT_LC2'))`

**Comment by nikosdion** [comment]
Thank you for the report! I actually chose to use an HTML helper in the component as it is more flexible.
