### ISSUE TITLE
Wrong time in module mod_engage_latest

### ISSUE THREAD

**Issue by pinochico** [akeeba/engage#202]
Time for comment is saved to DB in UTC (Gibraltar) format.

Etc. 21:35:46

But in Joomla global setup (or in user who created comment) is setup for 'offset' == TimeZone => Prague (UTC+2)

Modul show still time in UTC, not as 23:35:46.

But time for comment bottom article is with right TimeZone (yep, because in HtmlView.php for components/com_engage/tmpl/comments/default_list.php is a lot's function for right TimeZone, but in tmpl for module not).

**My Idea:**

1. Add code to USE section (top in template modules/mod_engage_latest/tmpl/default.php)

```
//Fix
use Akeeba\Component\Engage\Administrator\Helper\UserFetcher;
use Joomla\CMS\Date\Date;
use Joomla\CMS\User\User;
use DateTimeZone;
```

2. Add code for calculate right datetime:

```
//Fix
$user = !empty($comment->created_by) && empty($comment->name) ? UserFetcher::getUser($comment->created_by) : new User();
$siteTimezone = Factory::getApplication()->get('offset', 'UTC');
$zone = $user->guest ? $siteTimezone : $user->getParam('timezone', $siteTimezone);
$user->userTimezone = new DateTimeZone($zone);
$commentDate   = (new Date($comment->created))->setTimezone($user->userTimezone);
//END

```
3. change code for show datetime:4. 

`$commentDate->format(Text::_('DATE_FORMAT_LC2'), true)`

Result you can see on:

https://joomla4.easy.minion.cz/?view=article&id=1:clanek-cs-cz&catid=8

### System information

Engage v. 3.0.9
Module Engage Latest v. 3.0.9

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.1.2 Stable
* **PHP version**: 8.1.5
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: macOS
* **My device's Operating System version**: e.g. macOS Monterey
* **Browser**: Safari
* **Browser version**: 15.5

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 5.7.37-40-log
* **Server type**: Apache
* **Server version**: Linux wwwdevx.easy.minion.cz 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64
* **Hosting company / Local server**: ZCOM.cz
* **Server Operating System version**:

**Comment by nikosdion** [comment]
Addressed with commit https://github.com/akeeba/engage/commit/3595191140b9a273dcf0180f33ebf843fa933185
