### ISSUE TITLE
After install engagecache plugin throws an error

### ISSUE THREAD

**Issue by carcam** [akeeba/engage#23]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Install the package in a clean Joomla 3 install

### Expected result

Install success message

### Actual result

Site throwed the error:

> Class 'FOF30\Container\Container' not found 

### Troubleshooting already performed

Adding this line at the plugin code fixed the issue:

`include_once(JPATH_LIBRARIES . '/fof30/include.php');`

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.9.18
* **PHP version**: 7.4.0b (also on 7.3)
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: macOS
* **My device's Operating System version**: macOS Catalina
* **Browser**: Firefox
* **Browser version**: 76

**Comment by nikosdion** [comment]
Thank you for the PR!
