### ISSUE TITLE
500 error on saving comment

### ISSUE THREAD

**Issue by PMWilliams123** [akeeba/engage#236]
Please read the README.md in the repository's root and the support resources before submitting an issue.

**Write a comment and save**

Be specific. You may link to one or more screenshots or a video as long as it's not the only clue you leave. Use words to describe what happens.

What you believed should have happened following the steps you outlined above.

**captcha then return to the original page**

What actually happened.

**500 error**
but comment added to Akeba Engage: Comments 

Fatal error: Trait "Akeeba\Component\ATS\Administrator\Mixin\RunPluginsTrait" not found in /homepages/19/d531947429/htdocs/bookStore-Test/administrator/components/com_engage/src/Service/CacheCleaner.php on line 21
[ClassNotFoundError](http://bookstore-test.oddp.uk/index.php/component/engage/?task=comment.save#trace-box-1)
HTTP 500 Whoops, looks like something went wrong.
Attempted to load trait "RunPluginsTrait" from namespace "Akeeba\Component\ATS\Administrator\Mixin".
Did you forget a "use" statement for another namespace?
ExceptionStack Trace
Symfony\Component\ErrorHandler\Error\
ClassNotFoundError
in [/homepages/19/d531947429/htdocs/bookStore-Test/administrator/components/com_engage/src/Service/CacheCleaner.php ](http://bookstore-test.oddp.uk/index.php/component/engage/?task=comment.save)(line 21)
/** * Joomla cache cleaning service * * @since 3.2.0 */class CacheCleaner{    use RunPluginsTrait;    protected $app;
Please tell us about any troubleshooting you already performed and its results.

### System information

The currently installed Joomla! version is 4.3.0-alpha2-dev+pr.39491"‎4.3.0-alpha2-dev+pr.39491
PHP 8.0.26
MySQL 5.7

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.3.0-alpha2-dev+pr.39491"‎4.3.0-alpha2-dev+pr.39491
* **PHP version**:  8.0.26
* **Am I using HTTPS**: r No
* **Server Operating System**: Don't Know
* **My device's Operating System**: Windows 10 & Windows 11
* **My device's Operating System version**:  Win10 21H2, Win 11 22H2
* **Browser**: Chrome & Firefox
* **Browser version**: Chrome 108.0.5359.125 (Official Build) (64-bit), Firefox 108.0.1

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 5/7
* **Server type**: Apache, 
* **Server version**: N/A
* **Hosting company / Local server**:  Ionos
* **Server Operating System version**: N/A

**Comment by PMWilliams123** [comment]
http://bookstore-test.oddp.uk/index.php/dvds/a-fistful-of-dollars 
and see for yourself. I can give you an admin account if that helps

**Comment by nikosdion** [comment]
Yup, there is a typo in Akeeba Engage. I will fix it and release a new version.

**Comment by PMWilliams123** [comment]
Thanks...
