### ISSUE TITLE
Layout on Article edit screen

### ISSUE THREAD

**Issue by david-unwin** [akeeba/engage#237]
Just installed Engage on Joomla 4 site.
When editing an article the layout of the Engage pages looks strange.
![engage-edit screen](https://user-images.githubusercontent.com/95095238/210055974-d15457cf-2f3b-4e75-a877-0098e28311d9.png)
I can't see what I have done wrong?
Any ideas?

**Comment by nikosdion** [comment]
This has already been fixed in version 3.2.3. Please upgrade.
