### ISSUE TITLE
Layout on edit screen

### ISSUE THREAD

**Issue by david-unwin** [akeeba/engage#239]
Re previous issue which is now closed.
I am running the latest version 3.2.3 and I still have the problem.
![engage-edit screen](https://user-images.githubusercontent.com/95095238/210058470-eb7ecc21-3ad0-4e2d-b8cc-7eacb5e8b836.png)

**Comment by david-unwin** [comment]
![Extensions-engage](https://user-images.githubusercontent.com/95095238/210058699-3330fe88-46aa-49f8-8f23-446d534e02ff.png)

**Comment by nikosdion** [comment]
It looks like the fix I wrote is no longer there. I suspect something with Git got screwed up merging branches. Let me take a look.

**Comment by ManuelVoileux** [comment]
I had noticed , and I used the language translation system of Joomla to adjust. Actually , in French, the sentences do exist but are not displayed.

**Comment by nikosdion** [comment]
I mean, you are commenting on an issue describing the issue you have, where I said it's a bug and have linked to the fix. So, yes, of course you are seeing this issue since the code you are running is before I fixed this issue.

As I said before, I will release a new version **TOMORROW**.
