### ISSUE TITLE
Are they "comments" or "thoughts"

### ISSUE THREAD

**Issue by PMWilliams123** [akeeba/engage#257]
**Is your feature request related to a problem? Please describe.**

Throughout the constants and much of the legends are labelled "comments" except in the information links which are labelled "thoughts". I do not understand the reason for the inconsistency
 

**Describe the solution you'd like**

Either to have "comments" throughout or an option to choose "thoughts" or "comment".  

**Describe alternatives you've considered**

I have  tried language overrides with mixed success

**Why do you think this is relevant to people other than you**

Consistency is relevant to all surely as it avoids potential confusion. 

**Additional context**

It would be good indeed if people's comments were thought out bit calling them thoughts is unlikely to help ;-)

I have to add that this is not a criticism of the component or its creators, It is an excellent component which, as far as I can see, works extremely  well. As with any complex component it takes some getting ones head around - for me at least.

**Comment by nikosdion** [comment]
This is the **THIRD** notification you've sent to this project within 5 minutes. Which part of “Downloads and updates to the component are free of charge. WE DO NOT PROVIDE ANY END USER SUPPORT.” in the [README](https://github.com/akeeba/engage#features) of you not understand?

I reply to you when I have time and this is an incredibly busy month. I would have eventually gotten back to you.

By sending three notifications in five minutes you are effectively **demanding** my attention. Okay, you've got my undivided attention. I see someone who is not respecting my time and is hell bent to waste it with something trivial. Great job, you just got yourself banned.

**Comment by nikosdion** [comment]
FWIW the language used in Engage is copied from WordPress' comments feature. The reason is that Engage tries to be the drop-in replacement of WordPress' comments for people migrating from WordPress to Joomla. That's how it began its life.

As I have documented, you **CAN** change the language strings to read whatever you want. That's part of Joomla.
