### ISSUE TITLE
The file plg_content_engage.ini contains strings that are incorrect 

### ISSUE THREAD

**Issue by RobertvanderHulst** [akeeba/engage#263]
### Steps to reproduce the issue
Install Engage, and add comments. The text below the article on the featured articles page contains the word "thought" and not "comment".

### Expected result

"6 comments on “subject”

### Actual result

"6 thoughts on “subject”

### Troubleshooting already performed

I tried to replace this string with the language overrides for the site, but that did not work. 
When I added a override for the admin site it worked, but the strings are in the front end and not in the backend...

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.2.6
* **PHP version**: 8.0.27
* **Am I using HTTPS**: Yes 
* **Server Operating System**: Windows, Linux, macOS, Don't Know
* **My device's Operating System**: , Ubuntu
* **My device's Operating System version**: Windows
* **Browser**: FireFox, Chrome, Edge
* **Browser version**: All

**Comment by nikosdion** [comment]
This is intentional. The idea here is that Engage was a drop-in replacement to WordPress comments for people who come to Joomla from WordPress. Please read the docs for language overrides https://github.com/akeeba/engage/wiki/Language-overrides

**Comment by RobertvanderHulst** [comment]
This may be true, but I still think "thought" should be replaced with "comment" to be consistent with the rest.

**Comment by nikosdion** [comment]
I have changed the lang files. I don't know why people have this kind of visceral reaction to “thought” versus “comment”. If I were a psychologist I would probably find a correlation between that and the thoughtless comments flooding the Internet all over. But I'm not, I'm just a developer, and I'm tired of telling people that this is a stupidly trivial thing to change with documented instructions in the wiki.

**Comment by RobertvanderHulst** [comment]
Thanks
