### ISSUE TITLE
Ip filter does not work on back-end

### ISSUE THREAD

**Issue by NicolasDerumigny** [akeeba/engage#267]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Go in the back-end and try to fliter the results by ip.

### Expected result

One the comments with the filtered ip are displayed.

### Actual result

All comments are displayed.

### Troubleshooting already performed

[development/component/backend/src/Model/CommentsModel.php line 46](https://github.com/akeeba/engage/blob/development/component/backend/src/Model/CommentsModel.php#L461) should be set to `ParameterType::STRING`. Also, `$fltSearch` is not filled properly by [the back-end link](https://github.com/akeeba/engage/blob/development/component/backend/tmpl/comments/default.php#L176), preventing the patch to work either way.

### System information
Linux 5.15.84 on a Raspberry Pi 3B running Debian 11

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.2.8
* **PHP version**: 8.2.2
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Linux
* **My device's Operating System version**: arch Linux
* **Browser**: Firefox
* **Browser version**: 1100

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 10.5.18
* **Server type**: NginX
* **Server version**: 1.18.0 
* **Hosting company / Local server**: Local Server
* **Server Operating System version**: Debian 11

### Additional comments
It would also be nice to have the same button with user id filtering / mail adress.

**Comment by nikosdion** [comment]
Thank you for the heads up. I fixed it.

> It would also be nice to have the same button with user id filtering / mail adress.

Use the Search box. It support different prefixes, please read https://github.com/akeeba/engage/wiki/Comment-administration#filters

**Comment by NicolasDerumigny** [comment]
I have read it, but I was asking for a dedicated button as, for example, `ip:192.168.1.1 ` is not a valid query due to the last space. Thanks for the correction!
