### ISSUE TITLE
Kommentar Feld wird nicht angezeigt

### ISSUE THREAD

**Issue by mayo2222** [akeeba/engage#268]
Das Feld "KEINE KOMMENTARE" wird bereits bei meinem Beitrag anzeigt. Es ist die Kategorie eingerichtet dort sind Neue Kommentare erlaubt und auch beim Plugin steht alles auf ja. Kann es sein das man noch irgendein Element mit in den Beitrag einpflegen muss um neue Kommentare bekommen zu können oder gibt es eine ganz einfache Anleitung von der ich noch nichts weiß. 

Ich wäre für jede Hilfe dankbar !

**Comment by nikosdion** [comment]
Translating from German to English doesn't help me understand what you are talking about. My best guess is that you cannot see the editor to write a comment, something I have documented in https://github.com/akeeba/engage/wiki/Setting-up-your-HTML-editor

**Comment by mayo2222** [comment]
> Das Feld "KEINE KOMMENTARE" wird bereits bei meinem Beitrag anzeigt. Es ist die Kategorie eingerichtet dort sind Neue Kommentare erlaubt und auch beim Plugin steht alles auf ja. Kann es sein das man noch irgendein Element mit in den Beitrag einpflegen muss um neue Kommentare bekommen zu können oder gibt es eine ganz einfache Anleitung von der ich noch nichts weiß.
> 
> Ich wäre für jede Hilfe dankbar !


The field "NO COMMENTS" is already displayed in my post. The category is set up, new comments are allowed there and everything in the plugin is set to yes. Is it possible that I have to add some element to the post to be able to get new comments or is there a very simple instruction that I don't know about.

I would be grateful for any help!

**Comment by nikosdion** [comment]
Yeah, that's exactly what Google Translate gave me the first time around.

My best guess is that you cannot see the editor to write a comment, something I have documented in https://github.com/akeeba/engage/wiki/Setting-up-your-HTML-editor

**Comment by mayo2222** [comment]
Thanks, but i don't find this point :/ 
<img width="379" alt="Bildschirmfoto 2023-03-04 um 22 59 46" src="https://user-images.githubusercontent.com/126986950/222930568-e51ba7a8-c3b3-4efe-8e5b-ff15931cf2f9.png">
<img width="283" alt="Bildschirmfoto 2023-03-04 um 23 00 25" src="https://user-images.githubusercontent.com/126986950/222930571-a76d29c2-adb6-4e8e-bb64-09dd1191a6df.png">
<img width="987" alt="Bildschirmfoto 2023-03-04 um 23 00 30" src="https://user-images.githubusercontent.com/126986950/222930572-2cd026dd-63fd-4e85-9015-71984b0c12ee.png">

**Comment by mayo2222** [comment]
or maybe is the problem, that i use yootheme ?

**Comment by mayo2222** [comment]
thanks, i have the solution !
