### ISSUE TITLE
Possible spam error message is not correct and no mail is sent

### ISSUE THREAD

**Issue by NicolasDerumigny** [akeeba/engage#269]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Report as possible spam a comment.

### Expected result

The comment administrator are notified. A red message indicates that the message was successfully flagged as spam.

### Actual result

An error message is displayed, but the comment is correctly marked as spam. No mail is sent.

### Troubleshooting already performed
[component/backend/src/Controller/CommentsController.php L128)](https://github.com/akeeba/engage/blob/development/component/backend/src/Controller/CommentsController.php#L128) should be `if(!error)` for the correct message to appear. I haven't troubleshoot the mails.

### System information
Linux 5.15.84 on a Raspberry Pi 3B running Debian 11

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.2.8
* **PHP version**: 8.2.2
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Linux
* **My device's Operating System version**: arch Linux
* **Browser**: Firefox
* **Browser version**: 1100

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 10.5.18
* **Server type**: NginX
* **Server version**: 1.18.0 
* **Hosting company / Local server**: Local Server
* **Server Operating System version**: Debian 11

### Additional comments
An option or an override to notify only admin and not comment manager would be welcome.

**Comment by nikosdion** [comment]
Actually, that would be two lines after that: 

https://github.com/akeeba/engage/blob/0917b6b9c67e1bcaebadb22e5f993d132738227f/component/backend/src/Controller/CommentsController.php#L130

The last part of that line shouldn't be `'error'`.
