### ISSUE TITLE
Answering to a guest sends a mail to the comment author

### ISSUE THREAD

**Issue by NicolasDerumigny** [akeeba/engage#271]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Answer a guest comment with the option "notify user" on and "notify author" off.

### Expected result

A notification mail is send only to the guest image address.

### Actual result

A notification mail is send to both the guest and the new comment author.

### Troubleshooting already performed
None.

### System information
Linux 5.15.84 on a Raspberry Pi 3B running Debian 11

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.2.9
* **PHP version**: 8.2.2
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Linux
* **My device's Operating System version**: arch Linux
* **Browser**: Firefox
* **Browser version**: 1100

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 10.5.18
* **Server type**: NginX
* **Server version**: 1.18.0 
* **Hosting company / Local server**: Local Server
* **Server Operating System version**: Debian 11

### Additional comments
None

**Comment by nikosdion** [comment]
Thank you! Fixed with https://github.com/akeeba/engage/commit/b72428f328b92a9cb3f336607458076b3f97f516
