### ISSUE TITLE
Reply to is not taken into account when commenting on a thread spanning on several pages

### ISSUE THREAD

**Issue by NicolasDerumigny** [akeeba/engage#273]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Reply a comment on a thread spanning on multiple pages. For example, the top-level comment is on page 1, and answers are displays on page 2.

### Expected result

The new comment is shown as a reply to the last comment, with appropriate indentation.

### Actual result

The new comment is saved and displayed as a top-level comment (no answer / indentation).

### Troubleshooting already performed
None.

### System information
Linux 5.15.84 on a Raspberry Pi 3B running Debian 11

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.2.9
* **PHP version**: 8.2.2
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Linux
* **My device's Operating System version**: arch Linux
* **Browser**: Firefox
* **Browser version**: 1100

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 10.5.18
* **Server type**: NginX
* **Server version**: 1.18.0 
* **Hosting company / Local server**: Local Server
* **Server Operating System version**: Debian 11

### Additional comments
None

**Comment by nikosdion** [comment]
This is not a bug, it's the correct behaviour.

Any comment submitted is, by default, a top level comment _UNLESS_ you click on the Reply button for another comment. When you do the latter, the ID of that comment is sent with the comment form and becomes the parent comment of your comment.

This is something very well tested and I already confirmed it while answering [your previous issue](https://github.com/akeeba/engage/issues/272). See below:

<img width="950" alt="Screenshot 2023-03-31 at 10 32 55" src="https://user-images.githubusercontent.com/256041/229054025-a2b7795e-d3ea-46c1-9ea3-bbeda6d67a97.png">

**Comment by NicolasDerumigny** [comment]
I fully agree with what you say, but this seem not to answer my issue:

When answering a comment which is not a top-level comment and the top-level comment is _on a different page_ and the maximum comment depth is reached, the "Reply" button is not working properly and does nothing on click (probably because the real parent is not displayed on the page).

**Comment by nikosdion** [comment]
Yes, this is indeed the case. Unfortunately, I don't think I can realistically fix this without having to display all comments (remove pagination).
