### ISSUE TITLE
Date format setting in component options

### ISSUE THREAD

**Issue by jjnxpct** [akeeba/engage#278]
**Is your feature request related to a problem? Please describe.**
I would like some more control over the date format for the comments date. We now need to edit DATE_FORMAT_LC2 in our language overrides to change the date formatting. This might conflict with other parts of the site that also use this language string.

**Describe the solution you'd like**
I would like to have a setting in the component to format the comment date.

**Describe alternatives you've considered**
edit DATE_FORMAT_LC2

**Additional context**
This is nog a huge issue. Just a suggestion ;-)

**Comment by nikosdion** [comment]
You just need a template override: https://github.com/akeeba/engage/blob/development/component/frontend/tmpl/comments/default_list.php

The date format appears in two lines, 135 and 233.

I have decided not to add options for purely aesthetic feature requests. Having done that mistake with Akeeba Subscriptions well over a decade ago, it made the resulting code impossible to maintain. At the same time, nobody was happy with the dozens of options — users said there were either too many or not enough. Ultimately, template overrides are the only valid solution for anything that has to do with front-end presentation.

**Comment by jjnxpct** [comment]
OK, thanks Nicolas! I try to avoid overrides when it's just to add / change on little part of the view. Overrides are great but also need to be maintained when components get updated (sometimes). But i do get you point. So there's probably always a balance between arguments.

Anyway, compliments on this extension! I've been struggling with CComments for a long time now and decided I had enough... Searching for alternatives I found Akeeba Engage. And knowing Akeeba I thought: I can't go wrong with that ;-)

So thanks for another great component!

**Comment by nikosdion** [comment]
You won't see many updates to the view templates in the foreseeable future. Joomla 5 will be using Bootstrap 5.3 which I'm already using outside of Joomla; it does not need any structural changes. I've deliberately kept Engage simple so I don't have to update the view templates too often; ironically, if I were adding options to change purely aesthetic aspects I'd be updating these view templates all the friggin' time :)
