### ISSUE TITLE
Trying to Save the 'Login Module' option to (Do Not Display)

### ISSUE THREAD

**Issue by polygonrenegade** [akeeba/engage#28]
When I select the (Do Not Display) option and save it reverts to 'Login'
### Steps to reproduce the issue

Go to Component page
Click on 'Options'
Click on 'Advanced' tab
Select '(Do Not Disdplay)' option in Login Module field.
Click 'Save'

### Expected result

The Selection of (Do Not Display) is saved.

### Actual result

After save the value stored in Login Module has reverted to 'Login'

### Troubleshooting already performed

Tried saving other values then tried (Do Not Display) same result  - reverted to Login.
Logged out and back in and refreshed cache etc.. Still reverts.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.9.18
* **PHP version**: 7.3.17
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows
* **My device's Operating System version**: 10
* **Browser**: Chrome
* **Browser version**: Version 81.0.4044.138 (Official Build) (64-bit) (Currently up to date)

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 10.1.44-MariaDB
* **Server type**: LiteSpeed
* **Server version**: CLOUDLINUX 6.10 vmware 
* **Hosting company / Local server**: Rochen MCS
* **Server Operating System version**: v86.0.18

**Comment by nikosdion** [comment]
Already fixed in the development branch 😄  Joomla doesn't like saving an empty string value when there is a non-empty default setting for the field. The solution was to make the value for that option be -1 which is non empty, nonsensical and ultimately working fine 🤷‍♂️ 

I will release a new beta after a good night's sleep – it's almost 11pm in my timezone.

**Comment by nikosdion** [comment]
For project management reference: this issue was already resolved with commit https://github.com/akeeba/engage/commit/a4a4c82f075bf0dd8e90f62f658ea0e4a38c6c6e

**Comment by polygonrenegade** [comment]
Great - thanks for such a fast response especially at that time! Sleep well and no rush!

**Comment by nikosdion** [comment]
No problem! Thank you for taking the time to put the software through its paces :)
