### ISSUE TITLE
Edit comment in backend -> 'Save' and 'Save and close' are switched.

### ISSUE THREAD

**Issue by jjnxpct** [akeeba/engage#285]
When editing a comment in the backend (J 4.3.3) these buttons actions/tasks are 'switched':

- Pressing the 'Save' button results in saving the item and also closes it and returns to the list. (comment.save)
- Pressing the  'Save and close' button only save the item but does not close it. (comment.apply)

**Comment by nikosdion** [comment]
Thank you! It was indeed swapped in the View file.
