### ISSUE TITLE
Options page -> Font?

### ISSUE THREAD

**Issue by jjnxpct** [akeeba/engage#289]
In the backend options view of the extension the font changes half way the page. It think maybe a missing (or extra) tag in the dom somewhere?

![chrome_t0qo6D6KJG](https://github.com/akeeba/engage/assets/4346247/b44f0f32-b150-4461-844f-5c02a176d770)

Joomla 4.3.4
Engage 3.2.7
PHP 8.1.21 on Linux
HTTPS: Yes
User OS: Windows 11
User brwoser: Chrome 116.0.5845.111

**Comment by nikosdion** [comment]
Cannot reproduce across a total of six sites, two on live hosts, four on local hosts, on both Joomla! 4.3.3 and Joomla! 5.0.0-beta1.

Please note that this page is rendered by Joomla itself. We only provide an XML file with the names and types of the fields. There are no custom field types i.e. there is no code of ours producing any HTML on that page. Everything you see is produced by Joomla! itself, using its own core form field types and its core layouts.

You appear to have either found a bug in Joomla! (which I seriously doubt, as nobody has ever reported anything like that for any extension), or more likely you have found a bug in a Joomla! layout override on your site.

**Comment by jjnxpct** [comment]
Mmm, thats weird.... I will investigate some more -) Thanks for looking into this on your end.

**Comment by jjnxpct** [comment]
It turn out this was caused by dutch translation strings... I created a PR to fix this.

**Comment by nikosdion** [comment]
Thank you! Translations beyond English and Greek is something I can’t check myself for obvious reasons :)
