### ISSUE TITLE
Progressive Cache is not invalidated on guest comments

### ISSUE THREAD

**Issue by NicolasDerumigny** [akeeba/engage#297]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

- Set up the permission to allow guests (unidentified visitors) to comment
- Activate progressive caching
- Comment as guest

### Expected result
Guest can see the comment

### Actual result
Guest do not see the comment, but logged-in users do. 

### Troubleshooting already performed
Clearing manually the cache from the admin interface result in the comment being visible by guests.

### System information
Raspberry Pi 3 running latest Debian Arm build.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.3.4
* **PHP version**: 8.2.10
* **Am I using HTTPS**: Yes
* **Server Operating System**: Debian 10
* **My device's Operating System**: Arch Linux
* **My device's Operating System version**: Rolling
* **Browser**: Firefox
* **Browser version**: 118.0.1

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 10.5.19-MariaDB-0+deb11u2 
* **Server type**: Nginx
* **Server version**: Latests debian
* **Hosting company / Local server**: Local server
* **Server Operating System version**: Debian Arm

### Additional comments
Akeeba engage cache plugin is enabled, cache is set to 1 minute.

**Comment by nikosdion** [comment]
Enabled "System – Akeeba Engage cache support". As per its description:

> Ensures that comments appear correctly in the public frontend when caching is enabled and you're visiting the site as a guest. DO NOT DISABLE THIS PLUGIN if you have caching enabled on your site!

**Comment by NicolasDerumigny** [comment]
> Enabled "System – Akeeba Engage cache support". As per its description:
> 
> > Ensures that comments appear correctly in the public frontend when caching is enabled and you're visiting the site as a guest. DO NOT DISABLE THIS PLUGIN if you have caching enabled on your site!

The plugin is enabled, but the issue is still there.

**Comment by NicolasDerumigny** [comment]
![Screenshot_2023-10-09-08-12-14-462_org mozilla fennec_fdroid](https://github.com/akeeba/engage/assets/13258892/b6a0b712-11ec-42e4-801f-ad177f504685)

**Comment by NicolasDerumigny** [comment]
@nikosdion can you reopen the issue?

**Comment by nikosdion** [comment]
No need to because I just fixed it.

The problem is that Joomla will not load the content plugins when caching is enabled. Since the plugin handler to clear the content cache was in Engage's content plugin it would never run. I moved this code outside of the plugin so it will definitely run (tested). That was a “fun” little change sometime in the lifetime of Joomla 4.x.

**Comment by NicolasDerumigny** [comment]
👍 thanks for the rapidity!

**Comment by nikosdion** [comment]
You're welcome!
