### ISSUE TITLE
Comments module -> Link error

### ISSUE THREAD

**Issue by jjnxpct** [akeeba/engage#304]
Hi!

The links in the module give us this error when clicking them:

403 - We detected that your latest request may have been part of suspicious activity and has been blocked. If you believe you are getting this message in error please let us know through our site's contact form.

An example module link URL:

https://demo4.kerkintranet.nl/gemeentenieuws/test-artikel-ul-voor-de-app?lang=*&akengage_cid=80#akengage-comments-section

This part of the URL is causing this issue: lang=*

When I remove the language parameter from the URL it works fine. Also replacing it with the site language (lang=nl) there is no error.

Is Akeeba Admin tools blocking the URL or is this a server responsible for this? When we click the link a few time our IP gets blocked in Admin Tools. 

Kind regards,
Jip

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.4.1
* **PHP version**: 8.1.26
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows
* **My device's Operating System version**: 11
* **Browser**: Chrome
* **Browser version**:  120.0.6099.200

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 10.6.15 (MariaDB)
* **Server type**: Apache/2 litespeed
* **Server version**: x.y.z
* **Hosting company / Local server**: 
* **Server Operating System version**:

**Comment by jjnxpct** [comment]
In the Admin Tools firewall log the request is flagged as 'Suspicious Core Parameter'.

**Comment by nikosdion** [comment]
Yup, in this case the lang parameter should've been omitted. Fixed.

**Comment by jjnxpct** [comment]
Thanks for the quick Nicholas!
