### ISSUE TITLE
Compatibility with Flexicontent

### ISSUE THREAD

**Issue by alaingrach** [akeeba/engage#306]
Hello,
The Akeeba Engage component, appears to work with Flexicontent EXCEPT for permission to post comments or not for a specific category or article.
In fact, the "Comment" tab does not appear in the category or article administration, after installing Flexicontent. It is therefore not possible to prohibit or authorize comments specifically for this category or article.
Can you verify this issue? Or should I contact the Flexicontent developer?
THANKS.

**Comment by nikosdion** [comment]
As per the _first lines_ of the README shown in the [project's main page](https://github.com/akeeba/engage):

> Akeeba Engage is a simple comment solution for Joomla. It is meant to be used with core content (articles) only.
> 
> There is no intention of supporting non-core content.

**Comment by alaingrach** [comment]
Ok, thank's
