### ISSUE TITLE
Comply with Joomla 5 without compatibility plugin

### ISSUE THREAD

**Issue by NicolasDerumigny** [akeeba/engage#318]
**Is your feature request related to a problem? Please describe.**
Joomla 5 has a "Backward compatibility" plugin that provide access to former interfaces such as `JComponentHelper`. Disabling it break Akeeba Engage when new comments are posted, as this former class is used.

**Describe the solution you'd like**
Update Engage to get rid of `JComponentHelper` references.

**Describe alternatives you've considered**
Keep using the Backward Compatibility Plugin.

**Why do you think this is relevant to people other than you**
It will either way be required for future versions of Joomla.

**Additional context**
None.

**Comment by nikosdion** [comment]
It's not actually used directly, it's used in the XML forms in the `filter` attribute, e.g.:

```xml
        <field name="body"
               type="editor"
               label="COM_ENGAGE_COMMENTS_FILTER_BODY"
               default=""
               id="commentText"
               cols="50"
               rows="5"
               filter="JComponentHelper::filterText"
               buttons="true"
               hiddenLabel="true"
               required="true"
        />
```

Everything else was already replaced using Rector, the configuration for which you can see in the `rector.yaml` file.

I will address the forms in the next release.
