### ISSUE TITLE
Number "0" is not displayed in mod_engage_latest

### ISSUE THREAD

**Issue by NicolasDerumigny** [akeeba/engage#319]
### Steps to reproduce the issue

Comment with a sentence containing " 0 " such as "There are 0 reason for it to bug". Look at the latest comment module.

### Expected result

Latest comments module content shows "There are 0 reason for it to bug"

### Actual result

Latest comments module content shows "There are reason for it to bug"

### Troubleshooting already performed

[This line cause the issue.](https://github.com/akeeba/engage/blob/6cf8c16ff2962733dc00ae0735327e0982bb1a5c/component/backend/src/Service/Html/Engage.php#L116) as the filter removes "0". Change the line to `return !empty($x) || $x === "0";` and the bug is solved.

#### Mandatory information

* **Joomla! version**: 5.1.0
* **PHP version**:  8.2.18
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Arch
* **My device's Operating System version**: N.A.
* **Browser**: All
* **Browser version**: N.A.

#### Good to have information
* **MySQL version**: MariaDb 10.11.4
* **Server type**: NginX
* **Server version**: 1.22.1
* **Hosting company / Local server**: Local Raspberry Pi 4
* **Server Operating System version**: Debian 12

### Additional comments
Thanks, PHP!

**Comment by nikosdion** [comment]
Thank you
