### ISSUE TITLE
The form does not check the address mask of the mail

### ISSUE THREAD

**Issue by Kostelano** [akeeba/engage#34]
I do not know if this was done on purpose, but just in case I will inform you about it.

If guests are given the right to publish a comment, a form will appear in the article. In the email address field, you can enter just letters and the system will allow you to post a comment without checking the correctness of the email address.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/81932470-8b4f2480-95f4-11ea-96de-2632b5ef6af1.png)

### System information

* **Joomla! version**: 3.9.18
* **PHP version**: 7.3.2
* **Am I using HTTPS**: No (site on locale)
* **Server Operating System**: Windows
* **Browser**: Firefox

**Comment by nikosdion** [comment]
That's on purpose. There is no **reliable** way to validate an email address. Joomla's built-in email validator actually breaks on real world, valid email addresses I've seen (don't ask how I know...).

**Comment by nikosdion** [comment]
And please do not do a Google search and paste me links to what people _think_ is a reliable email address validation. I am perfectly aware of all the solutions and the fact that even the relevant [RFC 5322](https://tools.ietf.org/html/rfc5322) §3.4.1 throws its hands in the air with the following eloquent phrasing: “It is therefore incumbent upon implementations to conform to the syntax of addresses for the context in which they are used.”

**Comment by nikosdion** [comment]
Best I can do is change the field to the `email` (as I should have) so that the _browser_ gets to figure out how to best ensure that the text typed is likely to be an email address. Beyond that... just no.
