### ISSUE TITLE
There is no entry in the action log about adding a comment by a site guest

### ISSUE THREAD

**Issue by Kostelano** [akeeba/engage#35]
Something else :)

If a registered user added a comment, there is an entry in the action log. If the guest of the site added a comment, there is NO entry in the action log. Although I see that such an opportunity is provided.

I have not tried, but probably the same problem with respect to the line `Guest commenter with email {email} unsubscribed ...`.

The parameter in the Action Log plugin for GUESTS is enabled (all 3 parameters are actually enabled).

**Comment by nikosdion** [comment]
Joomla does not allow logging user actions for guest users. It needs a non-zero user ID or weird things happen. I should had already removed these options. Thank you for noticing, these options will be removed for the next version.
