### ISSUE TITLE
New comments published even though options set to New Comments = unpublished

### ISSUE THREAD

**Issue by polygonrenegade** [akeeba/engage#44]
### Steps to reproduce the issue

Main component options --> Basic Tab --> New comments set to 'Unpublished'
Permissions for public and guest to add Comments allowed.
Joomla category set to allow new comments.
Non-logged in public user completes the name, email, comment and captcha and hits the post new comment button.

![2020-05-29_214928](https://user-images.githubusercontent.com/65252079/83304221-61058580-a1f6-11ea-89cd-e3e2ad02e16f.jpg)
![2020-05-29_215031](https://user-images.githubusercontent.com/65252079/83304319-8eeaca00-a1f6-11ea-892a-108ed0723d23.jpg)
![2020-05-29_215100](https://user-images.githubusercontent.com/65252079/83304320-901bf700-a1f6-11ea-9543-54e860a5ca08.jpg)

### Expected result

New Comment created as unpublished and comment editors/moderators emailed to notify them to publish the comment.

### Actual result

Message shows 'Comment filed successfully' and comment created as published and is showing on the front-end page. (no admin email - author of article gets email to say comment is published).

### Troubleshooting already performed

Checked settings, tried with different emails and comments from mobile device such that no email match could be made to a user. checked not logged in. Checked permissions, options and category settings. Seems as though the setting of 'unpublished' just isn't doing anything and there is no override on the category.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.9.18
* **PHP version**: 7.3.18
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows & Android...
* **My device's Operating System version**: Windows 10 & Android 9
* **Browser**: Chrome
* **Browser version**: 83.0.4103.61

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 10.1.45
* **Server type**: Apache, LiteSpeed
* **Server version**: 
* **Hosting company / Local server**: Rochen MCS
* **Server Operating System version**: Cloudlinux

### Additional comments

Sorry if I have missed something!

**Comment by polygonrenegade** [comment]
Spot on - thanks a lot!

**Comment by nikosdion** [comment]
You're welcome and thank you for the heads up!
