### ISSUE TITLE
Mixed terminology

### ISSUE THREAD

**Issue by brianteeman** [akeeba/engage#45]
Sometimes the text refers to "submit a  comment"
Sometimes the text refers to "file a comment"

To me they should all be "post a comment"

Either way the text should be consistent.

**Comment by nikosdion** [comment]
I agree. I was fixing things as I was going. I'll check again how consistent it currently is.

**Comment by brianteeman** [comment]
Wasn't expecting a reply on a weekend. 

Why is it always so easy to spot this sort of thing in other people's code and not in my own

**Comment by nikosdion** [comment]
I was testing something so I was already on the computer :) This is an issue I had in mind to fix. Never a better time than now, I guess.
