### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by perronalain** [akeeba/engage#47]
How can I translate  "thoughts on "  in header of comments for an article ?
<img width="734" alt="2020-06-30_15-15-19ThoughtEngage" src="https://user-images.githubusercontent.com/50833917/86167494-9b5b8e80-bae4-11ea-8b97-36be80d7a438.png">

I can translate all other strings but I cannot find where is these strings: thoughts on

Can you help me ?

Thank you in advance.

**Comment by nikosdion** [comment]
It depends on the language. In English and Greek it translates well as "thoughts". My French is admittedly _very_ rusty but I think that you can't really translate it verbatim. In this case I would translate it as "comments on".

**Comment by nikosdion** [comment]
Note that a French translation has just been contributed. To avoid duplicating effort and wasting your time please proof-read the translation I merged into the development branch. Thank you!

**Comment by perronalain** [comment]
Thank you for your fast answer.
But I cannot find where I can translate "thoughts" in language file. Perhaps it is  a variable ?
I made a multi-search on my local copy for the string "thought" and "thoughts" with my program BBEDIT and it do not find any occurence. 

So if you can precise me where I can find this word for translating it, I will apreciate very much. 

Also, I read and copy the content of your language files and at this firt viewing it is very accurate, thank you. Here in Québec, Canada, the word "spam" is not used, we used in place "pourriel". That's fine because I always use the french translation for France and in this country, the word "spam" is correct. I can correct it without problem. 

Also I appreciate you use "courriel" for email .

So the unique problem is the translation of "thoughts" as seen in my screen capture above. If I can find it, I can translate it it is only a string and not a variable. 

Thank you in advance for all of your help. If you want I can verify the translation files more precisely. I can do that on evening here and place a new comment here after that. 

Have a good day and excuse my poor english. 

Alain Perron

**Comment by perronalain** [comment]
Sorry but I close by error the comment before.

**Comment by nikosdion** [comment]
The file you are looking for is `plugins/content/engage/language/en-GB/en-GB.plg_content_engage.ini`, the first three lines.

Please note that I did NOT write the French translation myself. It was sent to me by email, since the translator was getting confused by GitHub's interface and couldn't figure out how to make a Pull Request.

Your English is really good. _Far_ better than my French. Don't worry.

**Comment by perronalain** [comment]
But when I go to this folder I do not have a language folder. See the screen capture from my site. 
Thank you for your help. 
How can I correct that?
Probably this is the reason why I do not find this string with my multisearch !
<img width="1277" alt="2020-07-01_14-53-14EngagePlugin" src="https://user-images.githubusercontent.com/50833917/86281135-0c657980-bbab-11ea-81ea-989ebb7b47dd.png">

**Comment by nikosdion** [comment]
The folder name I gave you is in this repository. When you install the extension on your site the file is located in administrator/language/en-GB/en-GB.plg_content_engage.ini but you MUST NOT change it! It is the English language file, only used for the English language. You need to copy it to administrator/language/fr-FR/fr-FR.plg_content_engage.ini (if you're using the French (France) language) or administrator/language/fr-CA/fr-CA.plg_content_engage.ini (if you're using the French (Canada) language).

**Comment by perronalain** [comment]
Thank you for your help and patience. 
So I do not think that I have change anything from place to another just copy a file in english and copy it in the french folder.
But I deinstall all instances of Engage on my site, dowload again the version 1.0.0 from your site and reinstall it and I finally find the file for translating the string "thoughts" because the file is exactly where you indicate me "en-GB.plg_content_engage.ini
So I can find the term when I do a multi-search also so. I do not understand why I do not have this file at this place on first time. Perhaps because I install the version b2 before.... 
All works fine now .
Thank you again for your help.
