### ISSUE TITLE
Filter: Posted on --> IP address %s

### ISSUE THREAD

**Issue by Kostelano** [akeeba/engage#48]
Good day! In stable version 1.0.0, there is a string with a variable in the sort field. That probably shouldn't be.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/86483147-137fb980-bd5c-11ea-8755-37179fdc0d81.png)

Joomla 3.9.19
Engage 1.0.0 Stable

**Comment by nikosdion** [comment]
That's a good catch. There were too many sorting options shown. I forgot to filter them. I fixed it now. Thank you!
