### ISSUE TITLE
Spam icon does not appear in the comments list

### ISSUE THREAD

**Issue by Kostelano** [akeeba/engage#49]
**How to reproduce the problem**
1. Open the page with a list of comments in the Joomla control panel
2. Select 1 or more comments and click the "Possibble Spam" button in the toolbar

Pay attention to the screenshot - the spam icon is not displayed.
![Screenshot_1](https://user-images.githubusercontent.com/8440661/86495214-0923e680-bd81-11ea-9e11-43f5137bf655.png)

In addition, I noticed that the icons on the "Comments" tab and "Email Templates" are in a different style. Perhaps it would be prettier if they were in the same style.
![Screenshot_2](https://user-images.githubusercontent.com/8440661/86495202-01fcd880-bd81-11ea-8ce0-c60a77cd6424.png)

Joomla 3.9.19
Engage 1.0.0 Stable
Firefox 77.0.1 x64

**Comment by nikosdion** [comment]
I changed the column to use the same display style as the Email Templates page which also fixes the missing icon.
