### ISSUE TITLE
HTML code shown up in the page.

### ISSUE THREAD

**Issue by bkwchong** [akeeba/engage#53]
Hi,
  
  I have tried out akeeba engage 1.0.0. And I can see the html code issue,

![image](https://user-images.githubusercontent.com/4936635/88869805-21d7cd00-d257-11ea-8151-7540db1d7054.png)

  Appreciate if you can inform me any update to fix the issue. Thank you.

### Steps to reproduce the issue

Be specific. You may link to one or more screenshots or a video as long as it's not the only clue you leave. Use words to describe what happens.

1. Download and install the extension to Joomla 3.9.20. 
2. Keep all engage setting as default
3. Go to any of the article and the issue will appear

### Expected result

All the html codes will disappear.

### Actual result

HTML code appears

### Troubleshooting already performed

nothing, straight forward

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.9.20
* **PHP version**: 7.4.7
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows
* **My device's Operating System version**: Windows 10
* **Browser**: Chrome, 
* **Browser version**: 84.0.4147.105

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 7.4.7
* **Server type**: Apache
* **Server version**: 2.4.41 
* **Hosting company / Local server**: prepackaged local server 
* **Server Operating System version**: Ubuntu 20.04

**Comment by nikosdion** [comment]
This comes from the ARK editor. It has nothing to do with Akeeba Engage.

**Comment by bkwchong** [comment]
hi Nicholas,

  Thank you for the highlight.

Cheers,
Bryan
