### ISSUE TITLE
NL front-end translation

### ISSUE THREAD

**Issue by TLWebdesign** [akeeba/engage#55]
I took the time to translate the front-end. The back-end is a much bigger task and hope someone else can find the time to translate that part. At the moment it's unpossible for me to spend the time needed to translate the back-end.

Kind regards,

Tom

`COM_ENGAGE_COMMENTS_SECTION_HEADER="Reacties"

COM_ENGAGE_COMMENTS_HEADER_N_COMMENTS_0="Geen reacties"
COM_ENGAGE_COMMENTS_HEADER_N_COMMENTS_1="Eén reactie"
COM_ENGAGE_COMMENTS_HEADER_N_COMMENTS="%d reacties"

COM_ENGAGE_COMMENTS_LBL_PAGE="Pagina %s"
COM_ENGAGE_COMMENTS_LBL_VISIT_HTML_TO_COMMENT="Bekijk volledig artikel om te reageren"

COM_ENGAGE_COMMENTS_IP="Reactie geplaatst met IP: %s."
COM_ENGAGE_COMMENTS_TYPE_PUBLISHED=""
COM_ENGAGE_COMMENTS_TYPE_UNPUBLISHED="Gedepubliceerde reactie"
COM_ENGAGE_COMMENTS_TYPE_SPAM="Potentieel Spam"
COM_ENGAGE_COMMENTS_BTN_EDIT="Aanpassen"
COM_ENGAGE_COMMENTS_BTN_DELETE="Verwijderen"
COM_ENGAGE_COMMENTS_BTN_REPLY="Reageren"
COM_ENGAGE_COMMENTS_BTN_PUBLISH="Publiceren"
COM_ENGAGE_COMMENTS_BTN_UNPUBLISH="Depubliceren"
COM_ENGAGE_COMMENTS_BTN_MARKHAM="Geen Spam"
COM_ENGAGE_COMMENTS_BTN_MARKHAM_TITLE="Rapporteer reactie als geen spam en publiceer"
COM_ENGAGE_COMMENTS_BTN_MARKSPAM="Rappoteer en verwijder"
COM_ENGAGE_COMMENTS_BTN_MARKSPAM_TITLE="Rapporteer als SPAM en verwijder permanent"
COM_ENGAGE_COMMENTS_BTN_POSSIBLESPAM="Spam"
COM_ENGAGE_COMMENTS_BTN_POSSIBLESPAM_TITLE="Markeer de reactie als mogelijk spam"

COM_ENGAGE_COMMENTS_DELETE_PROMPT="Deze actie verwijdert PERMANENT het hele bericht inclusief reacties, ongeacht het niveau.\n\nVerwijderde reacties kunnen NIET teruggehaald worden.\n\n Weet u het heel zeker?"
COM_ENGAGE_COMMENTS_REPORTED_HAM="De reactie is gerapporteerd als niet-spam en gepubliceerd."
COM_ENGAGE_COMMENTS_REPORTED_SPAM="De reactie is gerapporteerd als spam en verwijderd."

COM_ENGAGE_COMMENTS_FORM_HEADER="Laat een reactie achter"
COM_ENGAGE_COMMENTS_FORM_INREPLYTO_LABEL="Als antwoord op"
COM_ENGAGE_COMMENTS_FORM_CANCELREPLY="Annuleren"
COM_ENGAGE_COMMENTS_FORM_NAME_LABEL="Naam"
COM_ENGAGE_COMMENTS_FORM_NAME_PLACEHOLDER="Jan Janssen"
COM_ENGAGE_COMMENTS_FORM_EMAIL_LABEL="E-mailadres"
COM_ENGAGE_COMMENTS_FORM_EMAIL_PLACEHOLDER="jan.jansen@voorbeeld.nl"
COM_ENGAGE_COMMENTS_FORM_REMEMBERME="Onthoud mijn naam en e-mail in deze browser"
COM_ENGAGE_COMMENTS_FORM_BTN_SUBMIT="Plaats uw reactie"
COM_ENGAGE_COMMENTS_FORM_LBL_ACCEPT="Ik geef toestemming dat mijn persoonlijke informatie opgeslagen en verwerkt wordt door deze website om de reactie te plaatsen alsmede mij te e-mailen bij antwoorden zoals in het Privacy Statement vermeld staat."

COM_ENGAGE_COMMENTS_ERR_NAME_AND_EMAIL_REQUIRED="U dient zowel uw naam als e-mailadres op te geven om te kunnen reageren."
COM_ENGAGE_COMMENTS_ERR_COMMENT_REQUIRED="Uw reactie moet tekst bevatten."
COM_ENGAGE_COMMENTS_ERR_CAPTCHA="De CAPTCHA heeft gefaald. Probeer het a.u.b. opnieuw om aan te tonen dat u een persoon bent en geen spambot."
COM_ENGAGE_COMMENTS_ERR_TOSACCEPT="U dient het vakje aan te vinken om ons expliciet toestemming te geven uw reactie te plaatsen."
COM_ENGAGE_COMMENTS_MSG_SUCCESS="Uw reactie was succesvol geplaatst."

COM_ENGAGE_COMMENTS_LOGIN_HEAD="Log in om te reageren"

COM_ENGAGE_COMMENTS_EDIT_HEADER="Pas een reactie aan"
COM_ENGAGE_COMMENTS_FORM_EDIT_NAME_LABEL="Reageerder's name"
COM_ENGAGE_COMMENTS_FORM_EDIT_EMAIL_LABEL="Reageerder's e-mailadres"
COM_ENGAGE_COMMENTS_FORM_EDIT_IP_LABEL="Reageerder's IP-adres"
COM_ENGAGE_COMMENTS_FORM_EDIT_BTN_SUBMIT="Opslaan"
COM_ENGAGE_COMMENTS_FORM_EDIT_BTN_CANCEL="Annuleren"
COM_ENGAGE_LBL_COMMENT_SAVED="De reactie is aangepast."

COM_ENGAGE_COMMENTS_ERR_BLATANT_SPAM="UW reactie is geidentificeerd als SPAM en is daarom meteen verwijderd."
COM_ENGAGE_LBL_COMMENT_DELETED="De reactie is verwijderd."

COM_ENGAGE_CRON_SPAM_MSG_DELETINGOLDSPAM_N="Verwijder spam ouder dan %u dagen."
COM_ENGAGE_CRON_SPAM_MSG_DELETINGOLDSPAM_N_1="Verwijd spam ouder dan %u dag."

COM_ENGAGE_CRON_SPAM_MSG_RUNNINGFOR_N="Loopt gedurende maximaal %u seconden."
COM_ENGAGE_CRON_SPAM_MSG_RUNNINGFOR_N_1="Loopt gedurende maximaal %u seconde."

COM_ENGAGE_CRON_SPAM_MSG_NOSPAM="Geen spam reacties ouder dan %u dagen gevonden."
COM_ENGAGE_CRON_SPAM_MSG_NOSPAM_1="Geen spam reacties ouder dan %u dag gevonden."

COM_ENGAGE_CRON_SPAM_MSG_DELETED="%u spam reacties zijn permanent verwijderd."
COM_ENGAGE_CRON_SPAM_MSG_DELETED_1="Eén spam reactie is permanent verwijderd."

COM_ENGAGE_COMMENTS_LBL_UNSUBSCRIBED="Het e-mailadres %s is uitgeschreven an e-mailnotificaties betreffende deze reactie. Bij een nieuwe reactie wordt u weer ingeschreven."
COM_ENGAGE_COMMENTS_ERR_ALREADY_UNSUBSCRIBED="U bent al uitgeschreven van dit gesprek."

COM_ENGAGE_COMMENTS_LBL_DELETEDCOMMENT="Reactie verwijderd omdat gebruikersaccount is verwijderd"
COM_ENGAGE_COMMENTS_LBL_DELETEDUSER="Verwijderd gebruikersaccount %d"`

**Comment by nikosdion** [comment]
I would be happy to include it if you could please make a Pull Request. I now refuse to create language files out of data posted in comments. When I do that, it appears that I was the original author of the language file. I'd rather have the language changes attributed to the right person and the only way to do that is though a Pull Request. Thank you!

**Comment by AANNQ** [comment]
I have translated to [zh-CN.com_engage.ini for my onw use. If someone need can be download at [HERE](https://github.com/AANNQ/TranslationToCN/blob/main/zh-CN.com_engage.ini)

**Comment by nikosdion** [comment]
@AANNQ Can you please make a Pull Request with your translation? As I explained, I cannot create language files out of data or links posted in comments. When I do that, it appears that I was the original author of the language file. I'd rather have the language changes attributed to the right person and the only way to do that is though a Pull Request. Thank you!

Also note that nobody reads closed issues like this one. Unless you guys file a PR which allows me to merge your languages nobody will be able to find them. Thank you for your understanding!
