### ISSUE TITLE
Registered Contact not Logged In

### ISSUE THREAD

**Issue by miamicityman** [akeeba/engage#60]
Per previous comment, I understand and agree that if a contact email is registered, the contact should be forced to log-in to participate with a comment to prevent associating comments to another contact.

Furthermore I see the "warning" on the back-end.

However, I don't see a similar notice in the front-end advising the un-logged registered visitor to first log-in when attempting to leave a comment.

If so, I think it would be a sensible feature.

Thanks,

**Comment by nikosdion** [comment]
Akeeba Engage allows you to publish a login module in the comment area, using the `engage-login` module position [as documented](https://github.com/akeeba/engage/wiki/Module-positions). The published module can have custom text; that's a core Joomla feature. If you do not publish a login module then _and only then_ does Akeeba Engage publish the default Joomla login module with its defaults settings.

Furthermore, you _can_ publish a Custom module in the `engage-before-reply` area per the same documentation page. The Custom module, a core Joomla feature, allows you to include any kind of HTML you want.

I prefer building software that's flexible and easily customisable by novices to the extent that's humanly possible. Putting a hardcoded message in the comments area is the exact opposite. If you don't like the wording you have to do a language override which is challenging unless someone tells you what is the language string you want to override. Controlling whether to display that message requires a template override which is fine — albeit cumbersome — for integrators but out of reach for novice and most intermediate users who really don't want to get their hands dirty with code. Why trip you over like that when you can simply publish modules, a core Joomla skill that's readily accessible to novices which doesn't require you to know anything at all about Joomla language strings, templates and PHP?

**Comment by miamicityman** [comment]
Understood. Got it. Works fine. Thank you.
<img width="580" alt="Screenshot_2021-01-11 Cursos virtuales sobre inspección y protección contra fuego Inpra Latina - la Zona de Pinturas(1)" src="https://user-images.githubusercontent.com/57761794/104211967-b0ee3100-5402-11eb-8af7-24a356f4d6d7.png">
