### ISSUE TITLE
Install/update 1.0.5 gives error Joomla 4 beta 8-dev php 8.0

### ISSUE THREAD

**Issue by breebee** [akeeba/engage#67]
### Steps to reproduce the issue

Tried to install *(update) to release 1.0.5 on a joomla 4 beta-8-dev php8.0 environment

### Expected result

Install successful

### Actual result

JInstaller: :Install: File does not exist /var/www/mms/tmp/install_601d2d8e0e952/engage-1.0.5/component/backend/vendor
Component Update: Failed to copy administrator files.
Error
Error installing component

### Troubleshooting already performed

Not sure what to troubleshoot

#### Mandatory information

* **Joomla! version**: 4.beta.8.dev
* **PHP version**: 8.0
* **Am I using HTTPS**:  No ( localhost )
* **Server Operating System**: Linux
* **My device's Operating System**: Linux
* **My device's Operating System version**: Ubuntu 18.04
* **Browser**: Firefox 
* **Browser version**: 86.0b5 64bit

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**:  10.1.47-MariaDB-0ubuntu0.18.04.1 
* **Server type**: NginX
* **Server version**: 1.14.0
* **Hosting company / Local server**: local
* **Server Operating System version**: e.g. Ubuntu 18.04

### Additional comments
I know 8.0 is not fully supported yet as it may be the cause, just trying to help report

**Comment by nikosdion** [comment]
Due to server issue I cannot upload the updates I started publishing this morning. I'm waiting for the server issue to be fixed before retrying.

**Comment by nikosdion** [comment]
FWIW PHP 8.0 _is_ a supported environment.
