### ISSUE TITLE
J4 Engage - Template Overrides

### ISSUE THREAD

**Issue by breebee** [akeeba/engage#68]
**Is your feature request related to a problem? Please describe.**
Unable to override Akeeba Engage via joomla 4 template file explorer. Mostly a mooj/profiles user however I am trying to adapt to using joomlas core template override mechanism which does not detect akeeba engage views.

**Describe the solution you'd like**
I would like to detect akeeba engage views via joomla 4 template file explorer to override.

**Describe alternatives you've considered**
FTP / SFTP / Local file manipulation

**Why do you think this is relevant to people other than you**
I believe akeeba engage will be the default joomla comment system the way it is built it is very well done. Handling overrides should be available with core joomla tool set / interface.

**Comment by nikosdion** [comment]
It already is and [I have ever documented it](https://github.com/akeeba/engage/wiki/Template-overrides).

**Comment by nikosdion** [comment]
Also note that Joomla 4 has a very opinionated view of what constitutes a view template. I am never going to implement THAT idiotic nonsense in my software. This is how we were writing software 15 years ago. All of my software uses Blade templates which are extensible and easier to maintain. Going back to the Dark Ages is something only idiots and core Joomla developers (not necessarily mutually exclusive groups of people) do.

**Comment by breebee** [comment]
**EDIT  - Ok I think I understand you mean some joomla core developers refuse to detect your files as views to which can be overridden afterwards. My appologies.. Thank you for the great work.

You must have not understood, it is not detectable TO override (not that overrides are supported) within joomla template file explorer->
![Screenshot_2021-02-05 Templates Customise (Frontend)](https://user-images.githubusercontent.com/13717576/107032579-5acb9e00-67b4-11eb-901c-c3a2723af37f.png)

**Comment by nikosdion** [comment]
OK, I can switch to standard Joomla templates which means that I have to create a special version of everything just for Akeeba Engage. This will cost 80,000 Euros per year in development time. Are you paying for it?

**Comment by nikosdion** [comment]
In any case, if you can't be arsed to read the documentation and can't figure out how to copy a file following instructions written for absolute idiots maybe you shouldn't be using my software. Enough with this bullshit.
