### ISSUE TITLE
First german translation available

### ISSUE THREAD

**Issue by NetSecond** [akeeba/engage#81]
Hi,

I have translated the english language in a first german language.
I think, it has to be checked and corrected before publishing.

How can I upload the changed files here ??
I have included the complete german language in the engage package too.

Best regards
NetSecond

**Comment by nikosdion** [comment]
The best way to do that is to fork the GitHub project (see the top right corner on this page when viewing my reply on GitHub through a desktop browser). This will create a copy of this repository under your account. Upload the files into the correct locations. GitHub will tell you there are such and such changes compared to the original (akeeba/engage development branch) and prompt you to create a Pull Request (a.k.a. PR). Create a PR and I'll see it here and merge it. This preserves the chain of authorship, i.e. the translation is publicly attributable to you to anyone looking in the Engage repository.

**Comment by patstraub** [comment]
Hi NetSecond
Have you but the German Translation to the files? Or can you send me this files?
Thanks
Patrick

**Comment by NetSecond** [comment]
Hi patsraub,
here is the complete updated package with german files:

!! Update 2021-05-23 !!

In case of implementation of the german files in Engage, the package is deleted here now.

**Comment by patstraub** [comment]
Awesome Gerd!
Lieben Dank für deine Arbeit…
Herzlichst
Patrick

**Comment by NetSecond** [comment]
Danke Patrick und gerne doch aber bitte berücksichtigen, dass das eine erste Version ist und noch Kleinigkeiten nicht ganz passen könnten.

To all: please be aware that this is my first version and there coud be some little typos or other things, you can maybe better translate.

**Comment by NetSecond** [comment]
EDIT:
In case of implementation, the link to the language files is not more needed here.
